# Generated by Django 5.1.1 on 2024-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0008_order_created_at_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
