# Generated by Django 5.1.1 on 2024-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0010_cartitem_selected_color_cartitem_selected_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery')], default='cod', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
